//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterAndLogin_LTQL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [MinLength(5)]
        [Required(ErrorMessage = " Username is required")]
        public string Username { get; set; }
        [MinLength(12)]
        [Required(ErrorMessage = "StudentName is required")]
        public string Password { get; set; }
    }
}
